# Generated by Django 5.0 on 2024-10-04 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 17, 37, 6, 62183, tzinfo=datetime.timezone.utc)),
        ),
    ]
